version: "2.4"

services:
  stampy-service:
    container_name: stampy-service
    build: ./stampy-app
    image: stampy-app:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://stampy-db:5432/stampy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - stampy-network
    depends_on:
      - stampy-db
  stampy-db:
    container_name: stampy-db
    image: postgres:latest
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - stampy-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stampy
    command: [ "postgres", "-c", "log_statement=all" ]

networks:
  stampy-network:
    driver: bridge
    name: stampy-network
